// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type HostScan struct {
	ID       int32
	Ip       netip.Addr
	ScanTime pgtype.Timestamptz
}

type ScanService struct {
	ID         int32
	HostScanID int32
	Port       int32
	Proto      string
	Service    pgtype.Text
	Banner     pgtype.Text
	Version    pgtype.Text
	Cpe        pgtype.Text
}

type ScanServiceVuln struct {
	ServiceID       int32
	VulnerabilityID int32
}

type Severity struct {
	ID   int32
	Name string
}

type Vulnerability struct {
	ID               int32
	Cve              string
	Score            pgtype.Numeric
	SeverityID       pgtype.Int4
	Description      pgtype.Text
	ExploitAvailable bool
	Link             pgtype.Text
}
