// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHostScan = `-- name: CreateHostScan :one
INSERT INTO host_scans (ip, scan_time)
VALUES ($1, $2)
RETURNING id
`

type CreateHostScanParams struct {
	Ip       netip.Addr
	ScanTime pgtype.Timestamptz
}

// CreateHostScan inserts a new scan record for a host and returns its ID
func (q *Queries) CreateHostScan(ctx context.Context, arg CreateHostScanParams) (int32, error) {
	row := q.db.QueryRow(ctx, createHostScan, arg.Ip, arg.ScanTime)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createService = `-- name: CreateService :one
INSERT INTO scan_services (
        host_scan_id,
        port,
        proto,
        service,
        banner,
        version,
        cpe
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateServiceParams struct {
	HostScanID int32
	Port       int32
	Proto      string
	Service    pgtype.Text
	Banner     pgtype.Text
	Version    pgtype.Text
	Cpe        pgtype.Text
}

// CreateService inserts a discovered open port into a scan record
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (int32, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.HostScanID,
		arg.Port,
		arg.Proto,
		arg.Service,
		arg.Banner,
		arg.Version,
		arg.Cpe,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLastHostScan = `-- name: GetLastHostScan :one
SELECT id,
    ip,
    scan_time
FROM host_scans
WHERE ip = $1
ORDER BY scan_time DESC
LIMIT 1
`

// GetLastHostScan returns the most recent scan record for a given IP
func (q *Queries) GetLastHostScan(ctx context.Context, ip netip.Addr) (HostScan, error) {
	row := q.db.QueryRow(ctx, getLastHostScan, ip)
	var i HostScan
	err := row.Scan(&i.ID, &i.Ip, &i.ScanTime)
	return i, err
}

const getServicesByScanID = `-- name: GetServicesByScanID :many
SELECT id,
    host_scan_id,
    port,
    proto,
    service,
    banner,
    version,
    cpe
FROM scan_services
WHERE host_scan_id = $1
`

// GetServicesByScanID returns all open ports discovered during a specific scan
func (q *Queries) GetServicesByScanID(ctx context.Context, hostScanID int32) ([]ScanService, error) {
	rows, err := q.db.Query(ctx, getServicesByScanID, hostScanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanService
	for rows.Next() {
		var i ScanService
		if err := rows.Scan(
			&i.ID,
			&i.HostScanID,
			&i.Port,
			&i.Proto,
			&i.Service,
			&i.Banner,
			&i.Version,
			&i.Cpe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicesWithVulnerabilities = `-- name: GetServicesWithVulnerabilities :many
SELECT s.id AS service_id,
    s.port,
    s.proto,
    s.service,
    s.banner,
    s.version,
    s.cpe,
    v.cve,
    v.score,
    v.exploit_available,
    v.link
FROM scan_services s
    LEFT JOIN scan_service_vulns sv ON s.id = sv.service_id
    LEFT JOIN vulnerabilities v ON sv.vulnerability_id = v.id
WHERE s.host_scan_id = $1
`

type GetServicesWithVulnerabilitiesRow struct {
	ServiceID        int32
	Port             int32
	Proto            string
	Service          pgtype.Text
	Banner           pgtype.Text
	Version          pgtype.Text
	Cpe              pgtype.Text
	Cve              pgtype.Text
	Score            pgtype.Numeric
	ExploitAvailable pgtype.Bool
	Link             pgtype.Text
}

// GetServicesWithVulnerabilities returns all services with vulnerabilities
func (q *Queries) GetServicesWithVulnerabilities(ctx context.Context, hostScanID int32) ([]GetServicesWithVulnerabilitiesRow, error) {
	rows, err := q.db.Query(ctx, getServicesWithVulnerabilities, hostScanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServicesWithVulnerabilitiesRow
	for rows.Next() {
		var i GetServicesWithVulnerabilitiesRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.Port,
			&i.Proto,
			&i.Service,
			&i.Banner,
			&i.Version,
			&i.Cpe,
			&i.Cve,
			&i.Score,
			&i.ExploitAvailable,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkServiceVuln = `-- name: LinkServiceVuln :exec
INSERT INTO scan_service_vulns (service_id, vulnerability_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkServiceVulnParams struct {
	ServiceID       int32
	VulnerabilityID int32
}

// LinkServiceVuln creates a many-to-many link between a service and a CVE
func (q *Queries) LinkServiceVuln(ctx context.Context, arg LinkServiceVulnParams) error {
	_, err := q.db.Exec(ctx, linkServiceVuln, arg.ServiceID, arg.VulnerabilityID)
	return err
}

const upsertVulnerability = `-- name: UpsertVulnerability :one
INSERT INTO vulnerabilities (
        cve,
        score,
        exploit_available,
        link
    )
VALUES ($1, $2, $3, $4) ON CONFLICT (cve) DO
UPDATE
SET score = EXCLUDED.score,
    exploit_available = EXCLUDED.exploit_available,
    link = EXCLUDED.link
RETURNING id
`

type UpsertVulnerabilityParams struct {
	Cve              string
	Score            pgtype.Numeric
	ExploitAvailable bool
	Link             pgtype.Text
}

// UpsertVulnerability inserts a new CVE or updates it if it already exists
func (q *Queries) UpsertVulnerability(ctx context.Context, arg UpsertVulnerabilityParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertVulnerability,
		arg.Cve,
		arg.Score,
		arg.ExploitAvailable,
		arg.Link,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
