// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
	"net/netip"
)

type Querier interface {
	// CreateHostScan inserts a new scan record for a host and returns its ID
	CreateHostScan(ctx context.Context, arg CreateHostScanParams) (int32, error)
	// CreateService inserts a discovered open port into a scan record
	CreateService(ctx context.Context, arg CreateServiceParams) (int32, error)
	// GetLastHostScan returns the most recent scan record for a given IP
	GetLastHostScan(ctx context.Context, ip netip.Addr) (HostScan, error)
	// GetServicesByScanID returns all open ports discovered during a specific scan
	GetServicesByScanID(ctx context.Context, hostScanID int32) ([]ScanService, error)
	// GetSeverityIDByName returns the ID of a severity given its name
	GetSeverityIDByName(ctx context.Context, name string) (int32, error)
	// GetVulnerabilitiesByServiceID returns all CVEs linked to a specific service
	GetVulnerabilitiesByServiceID(ctx context.Context, serviceID int32) ([]GetVulnerabilitiesByServiceIDRow, error)
	// LinkServiceVuln creates a many-to-many link between a service and a CVE
	LinkServiceVuln(ctx context.Context, arg LinkServiceVulnParams) error
	// UpsertVulnerability inserts a new CVE or updates it if it already exists
	UpsertVulnerability(ctx context.Context, arg UpsertVulnerabilityParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
