// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
	"net/netip"
)

type Querier interface {
	// CreateService inserts a discovered open port into a scan record
	CreateService(ctx context.Context, arg CreateServiceParams) (int32, error)
	DeleteServicesByScanID(ctx context.Context, hostScanID int32) error
	// GetHostScanByIP returns the most recent scan record for a given IP
	GetHostScanByIP(ctx context.Context, ip netip.Addr) (HostScan, error)
	// GetServicesWithVulnerabilities returns all services with vulnerabilities
	GetServicesWithVulnerabilities(ctx context.Context, hostScanID int32) ([]GetServicesWithVulnerabilitiesRow, error)
	// LinkServiceVuln creates a many-to-many link between a service and a CVE
	LinkServiceVuln(ctx context.Context, arg LinkServiceVulnParams) error
	// UpsertHostScan inserts a new scan record for a host and returns its ID
	UpsertHostScan(ctx context.Context, arg UpsertHostScanParams) (int32, error)
	// UpsertVulnerability inserts a new CVE or updates it if it already exists
	UpsertVulnerability(ctx context.Context, arg UpsertVulnerabilityParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
