apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: perimeter-postgres:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: $POSTGRES_SSLMODE
      postgresVersion: 1700
    isDefault: true
